### ISSUE TITLE
Question: What is nodesСontract in RouteLayerTestActivity?

### ISSUE THREAD

**Issue by askarsyzdykov** [onlylemi/MapView#17]
Hello, thanks for this project.

I don't understand - What is nodesСontract in RouteLayerTestActivity? How calculate it for my own map?

**Comment by AbdAllahBoda** [comment]
it's the relation between your nodes. check the following example:
nodesID: 1, 2, 3, 4, 5
nodeContract: (1, 5), (5, 1), (2, 3), (3, 2)


this means that you reach node #5 from node #1 and vice versa, same goes for the #2 and #3; but you can't reach #3 from #1 "it's not in the nodesContract array".

hope that helps :)

**Comment by askarsyzdykov** [comment]
Thanks man! You saved me
