### ISSUE TITLE
Node Contact list

### ISSUE THREAD

**Issue by amna-mirza** [onlylemi/MapView#4]
Hi,
Can you please explain how i could generate nodes and nodes contact list for a custom map to provide navigation?

**Comment by onlylemi** [comment]
hey @amna-mirza ,

First you need a indoor map and mark every crossing point between the road. These marks are `nodes` and two points of connection will be added `nodes contact`.

**Comment by amna-mirza** [comment]
Hey Jianbin Qi,
Thank you for your help. Really appreciated your project and your act of
help.


*Regards*
​

​​
Amna Mirza
Team Virtual Force
w
​
: www.virtual-force.com
e: amna.mirza@virtual-force.com
s: vf.amnamirza
<https://www.facebook.com/virtualforce1> <https://twitter.com/virtualforce1>
<https://www.linkedin.com/company/virtual-force>
