### ISSUE TITLE
[Feature proposal] Add support for GeoJson

### ISSUE THREAD

**Issue by pierreduchemin** [onlylemi/MapView#6]
GeoJson is an open standard format for mapping information (http://geojson.org/).
There are also initiatives like : https://github.com/asaarinen/indoor-json to override GeoJson and manage levels. However, it does not seems to be an active project anymore.

**Comment by onlylemi** [comment]
hey @pierreduchemin ,

It's ok! I will see it and try it. Thank you! 
Aslo you can fork this repository and commit your code.

**Comment by pierreduchemin** [comment]
@onlylemi of course, I will do if I get any interesting result ;)
