### ISSUE TITLE
How to generate ShortestPath on custom map

### ISSUE THREAD

**Issue by MrGlaucus** [onlylemi/MapView#8]
I tried to print all the PontF in getNodesContactList() and getNodesList() on the map as MarkLayers, and i can tell that the points in getNodesList() mean the point that you can turn, but the points in getNodesContactList() gathers on the Top-left corner ，which i cannot understand.What does that mean?

**Comment by onlylemi** [comment]
hey @MrGlaucus ,

u can look this image, from 1 to 22, these points all are `nodes`. And `nodes_contact` means adjacency relation between these points, so u need to set number for these points. eg: `5-1`, `5-9`, `5-6` in `nodes_contract`. 

![android_indoor_test_map](https://raw.githubusercontent.com/onlylemi/res/master/android_indoor_test_map.png)
